name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: Build with gcc
      run: ./workflow_build_linux.sh g++
      
    - name: Build with clang
      run: ./workflow_build_linux.sh clang
